server:
  port: 8081

spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/thesis_customer_service
    username: root
    password: 5599
  flyway:
    url: jdbc:mysql://localhost:3306/thesis_customer_service
    create-schemas: true
    user: root
    password: 5599
  cloud:
    function:
      definition: fetchUserContactInfo;
    stream:
      bindings:
        fetchUserContactInfo-in-0:
          destination: downstream.user-contact
          binder: kafka
        fetchUserContactInfo-out-0:
          destination: upstream.user-contact
          binder: kafka
  kafka:
    bootstrap-servers: localhost:9092


endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}