server:
  port: 8082
spring:
  application:
    name: inventory-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/thesis_inventory_service
    username: root
    password: 5599
  flyway:
    url: jdbc:mysql://localhost:3306/thesis_inventory_service
    user: root
    password: 5599
  cloud:
    function:
      definition: downstreamCheckInventoryFunction; downstreamProductPurchasedFunction; downstreamProductReturnedFunction
    stream:
      bindings:
        downstreamCheckInventoryFunction-in-0:
          destination: downstream.check-inventory
          binder: kafka
        downstreamCheckInventoryFunction-out-0:
          destination: upstream.check-inventory
          binder: kafka
        downstreamProductPurchasedFunction-in-0:
            destination: downstream.product-purchased
            binder: kafka
        downstreamProductReturnedFunction-in-0:
            destination: downstream.product-returned
            binder: kafka
  kafka:
    bootstrap-servers: localhost:9092

endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}